# Generated by Django 3.2.9 on 2021-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='web',
            field=models.CharField(default='', max_length=15),
        ),
    ]
